version: "3.4"
services:
  ravendb:
    image: ravendb/ravendb:5.1-ubuntu-latest
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://0.0.0.0:8080"
      - "RAVEN_ServerUrl=http://localravendb:8080"
      - "RAVEN_PublicServerUrl=http://localhost:8080"
      - "RAVEN_PublicServerUrl=http://localravendb:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
      - "RAVEN_ServerUrl_Tcp=tcp://localravendb:38888"
      - "RAVEN_PublicServerUrl_Tcp=tcp://localhost:38888"
      - "RAVEN_PublicServerUrl_Tcp=tcp://localravendb:38888"
        
  